### ISSUE TITLE
how do you activate the mod cause no button works and it doesn't work regularly 

### ISSUE THREAD

**Issue by AshVIII** [mycfFabricMods/TimberMod_r#4]

**Comment by 0xmycf** [comment]
Hello! You should be able to activate the mod via right click when holding an axe. If that doesn't work pls send me what Minecraft version you're using.

**Comment by chrisheib** [comment]
Have trouble getting this to run aswell:
I installed this server side only in latest fabric (correctly loaded according to log), but it doesn't work.
Can't chop down a tree with stone axe. Am I missing something?

**Comment by 0xmycf** [comment]
I uploaded a new version a few days ago you should try that. 

I do not know if this mod is server-side only but I've changed how the axes work, so new newer version might work Server side only. 

In the new version you can press right click to change the axes mode or press l to change the players mode (it allows you to disable the mod temporarily)

If neither bindings work you can change them in the keybindings option menu. 

I'd suggest the following:
Try to use the new version server side, if that doesn't work install on sever and on client side. Check the keybindings. 
If nothing works let me know again.

**Comment by chrisheib** [comment]
If possible I would love to use this with vanilla clients as purely serverside plugin, and that seems to not work so far. 

This other plugin works as server side mod with vanilla clients:
https://github.com/ricksouth/serilum-mc-mods/tree/master/sources-fabric/Stack%20Refill%20(Fabric)

Unfortunately I'm not experienced in writing minecraft mods at all, so I don't think I could add this myself currently.

**Comment by 0xmycf** [comment]
This is the only mod I actively work on and even that is limited to new Minecraft versions...

One of the earlier versions did work on severside only, I can provide you with a jar for that version, you'd loose some features though. 

Nonetheless I'll investigate this and see if I can make it purely Server side. This might take some time though.

**Comment by 0xmycf** [comment]
Ill switch to new [repository](https://github.com/mycfFabricMods/timber-v2) tomorrow. This will include a mod that works server side only. Only downside is that we lose the ability to have custom key binds there. I use the default of pressing the right mouse button for now. The Mods (client and server side) will be uploaded tomorrow too (on Modrinth and CurseForge).
